django_todo/urls.py
from django.contrib import admin
from django.urls import path
from todo.views import get_todo_list, add_item

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_todo_list, name='get_todo_list'),
    path('add', add_item, name='add')
]

todo/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    one = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return self.name

todo/views.py
from django.shortcuts import render
from .models import Item 

# Create your views here.


def get_todo_list(request):
    items = Item.objects.all()
    context = {
        'items' : items
    }
    return render(request, "todo/todo_list.html", context)

def add_item(request):
    return render(request, "todo/add_item.html")

todo/templates/todo/add_item.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Add a todo item:</h1>
    <form method="POST" action="add">
        <div>
            <p>
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" name="item_name" />
            </p>
        </div>
        <div>
            <p>
                <label for="id_one">Done:</label>
                <input type="checkbox" id="id_one" name="one" />
            </p>
        </div>
        <div>
            <button type="submit"> Add item</button> </form>
</body>

</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Things i need to do:</h1>

    <table>
        {% for item in items %}
        <tr>
            {% if item.one %}
            <td><strike>{{ item.name }}</strike></td>
            {% else %}
            <td>{{ item.name }}</td>
            {% endif %}
        </tr>
        {% empty %}
        <tr>
            <td>You have nothing todo</td>
        </tr>
        {% endfor %}
    </table>
    <a href="/add">Add an item</a>
</body>

</html>